apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow

resources:
- ../../base
- metadata-db-pvc.yaml
- metadata-db-deployment.yaml
- metadata-db-service.yaml

patches:
- path: patches/metadata-grpc-deployment.yaml

configMapGenerator:
- envs:
  - params.env
  name: metadata-db-parameters
secretGenerator:
- envs:
  - secrets.env
  name: metadata-db-secrets
generatorOptions:
  disableNameSuffixHash: true


images:
- name: mysql
  newName: mysql
  newTag: 8.0.3

replacements:
- source:
    fieldPath: metadata.name
    kind: Service
    name: metadata-db
    version: v1
  targets:
  - fieldPaths:
    - spec.template.spec.containers.0.args.1
    options:
      delimiter: =
      index: 1
    select:
      kind: Deployment
      name: metadata-grpc-deployment
      version: v1
