apiVersion: v1
kind: ConfigMap
metadata:
  name: ml-pipeline-driver-agent
  labels:
    workflows.argoproj.io/configmap-type: ExecutorPlugin
data:
  sidecar.automountServiceAccountToken: "true"
  sidecar.container: |
    name: driver-plugin
    image:  ntny/kf-driver:aplha123  
    ports:
      - containerPort: 8080
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: 250m
        memory: 512Mi
    securityContext:
      runAsNonRoot: true
      runAsUser: 65534
    volumeMounts:
    - name: argo-workflows-agent-ca-certificates
      mountPath: /etc/ssl/certs/ca-certificates
      readOnly: true
