apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ml-pipeline-viewer-crd
    {{- include "kubeflow-pipelines.labels" . | nindent 4 }}
  name: ml-pipeline-viewer-crd
spec:
  replicas: {{ .Values.viewerCrd.replicas }}
  selector:
    matchLabels:
      app: ml-pipeline-viewer-crd
  template:
    metadata:
      labels:
        app: ml-pipeline-viewer-crd
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
    spec:
      {{- include "kubeflow-pipelines.imagePullSecrets" . | nindent 6 }}
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
      - image: "{{ .Values.viewerCrd.image.repository }}:{{ .Values.viewerCrd.image.tag }}"
        imagePullPolicy: Always
        name: ml-pipeline-viewer-crd
        env:
        - name: MAX_NUM_VIEWERS
          value: {{ .Values.viewerCrd.maxNumViewers | quote }}
        {{- if .Values.multiUser.enabled }}
        - name: NAMESPACE
          value: ""
        {{- else }}
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        {{- end }}
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 0
          capabilities:
            drop:
            - ALL
        {{- with .Values.viewerCrd.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      serviceAccountName: ml-pipeline-viewer-crd-service-account
      {{- with ((kindIs "invalid" .Values.viewerCrd.nodeSelector) | ternary .Values.global.nodeSelector .Values.viewerCrd.nodeSelector) }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with ((kindIs "invalid" .Values.viewerCrd.tolerations) | ternary .Values.global.tolerations .Values.viewerCrd.tolerations) }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with ((kindIs "invalid" .Values.viewerCrd.affinity) | ternary .Values.global.affinity .Values.viewerCrd.affinity) }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
