apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
# Note, we do not explicitly separate cluster-scoped resources for cluster installation,
# because people who deploy cluster-scoped resources should be the same as who deploys
# namespaced resources.
- ../../upstream/manifests/base/crds
- ../../upstream/manifests/cluster-install/workflow-controller-rbac
- ../../base
