{{- if and .Values.compat.enabled .Values.compat.mysql.deployment (not .Values.mysql.enabled) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: {{ .Release.Namespace }}
  labels:
    app: mysql
    {{- if .Values.compat.applicationCrdIdLabel }}
    application-crd-id: kubeflow-pipelines
    {{- end }}
    {{- include "kubeflow-pipelines.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
        {{- if .Values.compat.applicationCrdIdLabel }}
        application-crd-id: kubeflow-pipelines
        {{- end }}
    spec:
      serviceAccountName: mysql
      containers:
        - name: mysql
          image: "mysql:8.4"
          args:
            - --datadir
            - /var/lib/mysql
            - --authentication-policy=mysql_native_password
            - --mysql-native-password=ON
            - --disable-log-bin
          env:
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "true"
          ports:
            - containerPort: 3306
              name: mysql
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 999
            runAsGroup: 999
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-persistent-storage
          resources:
            requests:
              cpu: 100m
              memory: 800Mi
      securityContext:
        fsGroup: 999
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
{{- end }}
