apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# Minimal CRDs omit schema validation, recommended for production cluster.
- https://github.com/argoproj/argo-workflows/manifests/base/crds/minimal?ref=v3.7.3
