# Change resyncPeriodSeconds to 1 hour from insane 20 seconds  
# For some crazy reasons the crd name is often different...  
# CRD is network-attachment-definitions while the instance is NetworkAttachmentDefinition
apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: kubeflow-pipelines-profile-controller
spec:
  generateSelector: true
  resyncPeriodSeconds: 3600
  parentResource:
    apiVersion: v1
    resource: namespaces
  childResources:
  - apiVersion: v1
    resource: secrets
    updateStrategy:
      method: OnDelete
  - apiVersion: v1
    resource: configmaps
    updateStrategy:
      method: OnDelete
  - apiVersion: apps/v1
    resource: deployments
    updateStrategy:
      method: InPlace
  - apiVersion: v1
    resource: services
    updateStrategy:
      method: InPlace
  - apiVersion: k8s.cni.cncf.io/v1
    resource: network-attachment-definitions
    updateStrategy:
      method: InPlace
  - apiVersion: v1
    resource: limitranges
    updateStrategy:
      method: InPlace
  - apiVersion: kubeflow.org/v1alpha1
    resource: poddefaults
    updateStrategy:
      method: InPlace
  - apiVersion: networking.k8s.io/v1
    resource: networkpolicies
    updateStrategy:
      method: InPlace
  hooks:
    sync:
      webhook:
        url: http://kubeflow-pipelines-profile-controller/sync

