apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipelines-profile-controller-admin
  namespace: kubeflow
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pipelines-profile-controller-admin-clusterrole
rules:
  - apiGroups: [""]
    resources: ["serviceaccounts"]
    verbs: ["create", "get", "list", "watch", "update", "delete"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["roles", "rolebindings"]
    verbs: ["create", "get", "list", "watch", "update", "delete"]
  - apiGroups: [ "" ]
    resources: [ "configmaps" ]
    verbs: [ "get", "list", "watch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pipelines-profile-controller-admin-binding
subjects:
  - kind: ServiceAccount
    name: pipelines-profile-controller-admin
    namespace: kubeflow
roleRef:
  kind: ClusterRole
  name: pipelines-profile-controller-admin-clusterrole
  apiGroup: rbac.authorization.k8s.io