# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true

required = [
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "github.com/golang/protobuf/protoc-gen-go",
  "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger",
  "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway",
  "github.com/go-swagger/go-swagger/cmd/swagger",
]

[[constraint]]
  name = "github.com/argoproj/argo"
  version = "2.2.0"

[[constraint]]
  name = "github.com/cenkalti/backoff"
  version = "2.0.0"

[[constraint]]
  name = "github.com/fsnotify/fsnotify"
  version = "1.4.7"

[[override]]
  name = "github.com/ghodss/yaml"
  branch = "master"

[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  version = "1.4.0"


[[constraint]]
  name = "github.com/google/uuid"
  version = "0.2.0"

[[constraint]]
  name = "github.com/jinzhu/gorm"
  version = "1.9.1"

[[constraint]]
  name = "github.com/kataras/iris"
  version = "10.6.6"

[[constraint]]
  name = "github.com/mattn/go-sqlite3"
  version = "1.9.0"

[[constraint]]
  name = "github.com/minio/minio-go"
  version = "6.0.5"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/robfig/cron"
  version = "1.1.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.6"

[[override]]
  name = "github.com/spf13/viper"
  version = "1.2.1"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.13.0"

[[constraint]]
  branch = "release-1.9"
  name = "k8s.io/api"

[[constraint]]
  branch = "release-1.9"
  name = "k8s.io/apimachinery"

[[constraint]]
  name = "k8s.io/kubernetes"
  version = "1.11.1"

[prune]
  go-tests = true
  unused-packages = true

   [[prune.project]]
    name = "k8s.io/code-generator"
    unused-packages = false

   [[prune.project]]
    name = "github.com/golang/protobuf"
    unused-packages = false

   [[prune.project]]
    name = "github.com/grpc-ecosystem/grpc-gateway"
    unused-packages = false

   [[prune.project]]
    name = "github.com/go-swagger/go-swagger"
    unused-packages = false

[[override]]
  branch = "release-1.11"
  name = "k8s.io/apimachinery"

[[override]]
  branch = "release-1.11"
  name = "k8s.io/api"

[[override]]
  name = "k8s.io/client-go"
  # revision for tag "kubernetes-1.11.1"
  revision = "59698c7d9724b0f95f9dc9e7f7dfdcc3dfeceb82"

[[override]]
  name = "github.com/spf13/pflag"
  version = "1.0.1"

[[override]]
  name = "k8s.io/code-generator"
  # revision for tag "kubernetes-1.11.1"
  revision = "6702109cc68eb6fe6350b83e14407c8d7309fd1a"

[[override]]
  name = "github.com/grpc-ecosystem/grpc-gateway"
  revision = "8aa3d3f00fbaea619d864e688cd045497aa30fe8"

[[override]]
  name = "github.com/golang/protobuf"
  revision = "1918e1ff6ffd2be7bed0553df8650672c3bfe80d"

[[override]]
  name = "github.com/go-swagger/go-swagger"
  version = "v0.17.0"

[[override]]
  name = "github.com/go-openapi/analysis"
  version = "v0.17.2"

[[override]]
  name = "google.golang.org/genproto"
  revision = "bd91e49a0898e27abb88c339b432fa53d7497ac0"


[[constraint]]
  name = "github.com/google/go-cmp"
  version = "0.2.0"
