apiVersion: v1
kind: ConfigMap
metadata:
  name: kfp-launcher
  labels:
    {{- include "kubeflow-pipelines.labels" . | nindent 4 }}
data:
  defaultPipelineRoot: {{ .Values.config.defaultPipelineRoot | quote }}
