{{- if not .Values.objectStoreSecret.existingSecret }}
kind: Secret
apiVersion: v1
metadata:
  name: mlpipeline-minio-artifact
  labels:
    {{- include "kubeflow-pipelines.labels" . | nindent 4 }}
stringData:
  {{ .Values.objectStoreSecret.accessKeyKey }}: {{ .Values.objectStoreSecret.accessKey }}
  {{ .Values.objectStoreSecret.secretKeyKey }}: {{ .Values.objectStoreSecret.secretKey }}
{{- end }}
