apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: ml-pipeline
    {{- include "kubeflow-pipelines.labels" . | nindent 4 }}
  name: kubeflow-pipelines-public
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubeflow-pipelines-public
subjects:
- kind: Group
  apiGroup: rbac.authorization.k8s.io
  name: system:authenticated
