apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cache-deployer-role.yaml
  - cache-deployer-rolebinding.yaml
  - cache-deployer-deployment.yaml
commonLabels:
  app: cache-deployer
images:
  - name: ghcr.io/kubeflow/kfp-cache-deployer
    newTag: 2.4.1
