apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow

resources:
- ../../base
- metadata-db-pvc.yaml
- metadata-db-deployment.yaml
- metadata-db-service.yaml

patches:
- path: patches/metadata-grpc-deployment.yaml

configMapGenerator:
- envs:
  - params.env
  name: metadata-postgres-db-parameters
secretGenerator:
- envs:
  - secrets.env
  name: metadata-postgres-db-secrets
generatorOptions:
  disableNameSuffixHash: true

images:
- name: postgres
  newName: postgres
  newTag: 14.7-alpine3.17

replacements:
- source:
    fieldPath: metadata.name
    kind: Service
    name: metadata-postgres-db
    version: v1
  targets:
  - fieldPaths:
    - spec.template.spec.containers.0.args.2
    options:
      delimiter: =
      index: 1
    select:
      name: metadata-grpc-deployment
      kind: Deployment
      version: v1
