apiVersion: v1
kind: Service
metadata:
  labels:
    app: seaweedfs
    component: volume
  name: seaweedfs-volume
spec:
  ports:
  - name: swfs-volume
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: swfs-volume-18080
    port: 18080
    protocol: TCP
    targetPort: 18080
  selector:
    app: seaweedfs
    component: volume
