# SeaweedFS service - provides S3-compatible storage for Kubeflow Pipelines.
# Port 9000 is included for backward compatibility with configs that expect the legacy port.
apiVersion: v1
kind: Service
metadata:
  name: seaweedfs
  namespace: kubeflow
spec:
  ports:
  - name: http-iam
    port: 8111
    protocol: TCP
    targetPort: 8111
  - name: http-s3
    port: 8333
    protocol: TCP
    targetPort: 8333
  - name: http-s3-compat
    port: 9000
    protocol: TCP
    targetPort: 8333
  - name: http-master
    port: 9333
    protocol: TCP
    targetPort: 9333
  - name: grpc-master
    port: 19333
    protocol: TCP
    targetPort: 19333
  - name: grpc-filer
    port: 18888
    protocol: TCP
    targetPort: 18888
  - name: http-filer
    port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: seaweedfs
