[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "kfp"
dynamic = ["version"]
description = "Kubeflow Pipelines SDK"
readme = "README.md"
requires-python = ">=3.9.0"
license = {text = "Apache-2.0"}
authors = [
    { name = "The Kubeflow Authors" },
]
classifiers = [
    "Intended Audience :: Developers",
    "Intended Audience :: Education",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Software Development",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
dependencies = [
    "click >= 8.0.0",
    "click-option-group >= 0.5.0", 
    "docstring-parser >= 0.7.3",   
    "kfp-server-api >= 2.0.0, < 3.0.0dev", # Added
    "google-api-python-client >= 1.7.8, < 3.0.0dev",
    "google-auth >= 1.6.1, < 3.0.0dev",
    "google-cloud-storage >= 1.20.0, < 3.0.0dev",
    "jsonschema >= 3.0.1",
    "kubernetes >= 8.0.1, < 27.0.0",
    "PyYAML >= 5.3",
    "requests-toolbelt >= 0.8.0, < 1.0.0",
    "tabulate >= 0.8.6, < 1.0.0",
    "urllib3 < 2.0.0",
    "protobuf >= 3.13.0",
]

[project.optional-dependencies]
kubernetes = ["kfp-kubernetes"]
notebooks = [
    "nbclient >= 0.10, < 1",
    "ipykernel >= 6, < 7",
    "jupyter_client >= 7, < 9",
]
docker = ["docker"]
all = [
    "kfp[kubernetes,notebooks,docker]"
]

[project.urls]
Documentation = "https://kubeflow-pipelines.readthedocs.io/en/stable/"
"Bug Tracker" = "https://github.com/kubeflow/pipelines/issues"
Source = "https://github.com/kubeflow/pipelines/tree/master/sdk"
Changelog = "https://github.com/kubeflow/pipelines/blob/master/sdk/RELEASE.md"

[project.scripts]
dsl-compile = "kfp.cli.compile_:main"
kfp = "kfp.cli.__main__:main"

[tool.hatch.version]
path = "kfp/version.py"

[tool.hatch.build.targets.wheel]
packages = ["kfp"]