apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: pipelineversions.pipelines.kubeflow.org
  labels:
    {{- include "kubeflow-pipelines.labels" . | nindent 4 }}
webhooks:
- name: pipelineversions.pipelines.kubeflow.org
  rules:
  - operations:
    - CREATE
    - UPDATE
    apiGroups:
    - pipelines.kubeflow.org
    apiVersions:
    - v2beta1
    resources:
    - pipelineversions
    scope: Namespaced
  admissionReviewVersions:
  - v1
  sideEffects: None
  failurePolicy: Fail
  clientConfig:
    service:
      name: ml-pipeline
      namespace: {{ .Release.Namespace }}
      path: /webhooks/validate-pipelineversion
      port: 8443
