apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/crds
  - ../../platform-agnostic
  - ../base-tls-certs/

namespace: kubeflow

patches:
  - path: patches/ml-pipeline-apiserver-deployment.yaml
    target:
      kind: Deployment
      name: ml-pipeline
  - path: patches/ml-pipeline-apiserver-service.yaml
    target:
      kind: Service
      name: ml-pipeline
  - path: patches/ml-pipeline-scheduledworkflow-deployment.yaml
    target:
      kind: Deployment
      name: ml-pipeline-scheduledworkflow
  - path: patches/ml-pipeline-persistenceagent-deployment.yaml
    target:
      kind: Deployment
      name: ml-pipeline-persistenceagent
  - path: patches/ml-pipeline-ui-deployment.yaml
    target:
      kind: Deployment
      name: ml-pipeline-ui
