{{- if .Values.multiUser.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: metadata-grpc
  labels:
    {{- include "kubeflow-pipelines.labels" . | nindent 4 }}
spec:
  gateways:
  - kubeflow-gateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /ml_metadata
    rewrite:
      uri: /ml_metadata
    route:
    - destination:
        host: metadata-envoy-service.{{ .Release.Namespace }}.svc.cluster.local
        port:
          number: 9090
{{- end }}
