{{- if .Values.multiUser.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubeflow-pipelines-profile-controller-env
  labels:
    {{- include "kubeflow-pipelines.labels" . | nindent 4 }}
data:
  DISABLE_ISTIO_SIDECAR: {{ .Values.profileController.disableIstioSidecar | quote }}
{{- end }}
