apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - metadata-configmap.yaml
  - metadata-deployment.yaml
  - metadata-service.yaml
  - metadata-envoy-deployment.yaml
  - metadata-envoy-service.yaml
