kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  # Expose the UI, MySQL, MLMD, SeaweedFS, and the visualization server
  extraPortMappings:
  - containerPort: 30300
    hostPort: 3000
  - containerPort: 30330
    hostPort: 3306
  - containerPort: 30808
    hostPort: 8080
  - containerPort: 30900
    hostPort: 9000
  - containerPort: 30889
    hostPort: 8889
