images:
  apiserver: gcr.io/ml-pipeline/google/pipelines/apiserver:dummy
  argoexecutor: gcr.io/ml-pipeline/google/pipelines/argoexecutor:dummy
  argoworkflowcontroller: gcr.io/ml-pipeline/google/pipelines/argoworkflowcontroller:dummy
  cloudsqlproxy: gcr.io/ml-pipeline/google/pipelines/cloudsqlproxy:dummy
  frontend: gcr.io/ml-pipeline/google/pipelines/frontend:dummy
  metadataserver: gcr.io/ml-pipeline/google/pipelines/metadataserver:dummy
  minio: gcr.io/ml-pipeline/google/pipelines/minio:dummy
  mysql: gcr.io/ml-pipeline/google/pipelines/mysql:dummy
  persistenceagent: gcr.io/ml-pipeline/google/pipelines/persistenceagent:dummy
  proxyagent: gcr.io/ml-pipeline/google/pipelines/proxyagent:dummy
  scheduledworkflow: gcr.io/ml-pipeline/google/pipelines/scheduledworkflow:dummy
  viewercrd: gcr.io/ml-pipeline/google/pipelines/viewercrd:dummy
  metadataenvoy: gcr.io/ml-pipeline/google/pipelines/metadataenvoy:dummy
  metadatawriter: gcr.io/ml-pipeline/google/pipelines/metadatawriter:dummy
  cacheserver: gcr.io/ml-pipeline/google/pipelines/cacheserver:dummy
  cachedeployer: gcr.io/ml-pipeline/google/pipelines/cachedeployer:dummy

executor:
  emissary: true
gcpDefaultConfigName: "gcp-default-config"
managedstorage:
  enabled: false
  cloudsqlInstanceConnectionName: ""
  gcsBucketName: ""
  databaseNamePrefix: ""
  dbUsername: 'root'
  dbPassword: ''
