images:
  apiserver: gcr.io/ml-pipeline/google/pipelines/apiserver:0.1.31
  argoexecutor: gcr.io/ml-pipeline/google/pipelines/argoexecutor:0.1.31
  argoworkflowcontroller: gcr.io/ml-pipeline/google/pipelines/argoworkflowcontroller:0.1.31
  cloudsqlproxy: gcr.io/ml-pipeline/google/pipelines/cloudsqlproxy:0.1.31
  frontend: gcr.io/ml-pipeline/google/pipelines/frontend:0.1.31
  metadataserver: gcr.io/ml-pipeline/google/pipelines/metadataserver:0.1.31
  minio: gcr.io/ml-pipeline/google/pipelines/minio:0.1.31
  mysql: gcr.io/ml-pipeline/google/pipelines/mysql:0.1.31
  persistenceagent: gcr.io/ml-pipeline/google/pipelines/persistenceagent:0.1.31
  proxyagent: gcr.io/ml-pipeline/google/pipelines/proxyagent:0.1.31
  scheduledworkflow: gcr.io/ml-pipeline/google/pipelines/scheduledworkflow:0.1.31
  viewercrd: gcr.io/ml-pipeline/google/pipelines/viewercrd:0.1.31
  visualizationserver: gcr.io/ml-pipeline/google/pipelines/visualizationserver:0.1.31
  metadataenvoy: gcr.io/ml-pipeline/google/pipelines/metadataenvoy:0.1.31

gcpSecretName: "user-gcp-sa"
serviceAccountCredential: ""

managedstorage:
  enabled: false
  cloudsqlInstanceConnectionName: null
  # gcsBucketName should be determined by cloudsqlInstanceConnectionName to make
  # sure user is always using a valid pair of connection name + gcs bucket name.
  #
  # gcsBucketName is used in two places, so I wrote a template string here that
  # can be evaluated in each place.
  gcsBucketName: '{{ if .Values.managedstorage.databaseNamePrefix }}{{ printf "%s-%s" .Values.managedstorage.cloudsqlInstanceConnectionName .Values.managedstorage.databaseNamePrefix | replace ":" "-" | trunc 50 }}{{ else }}{{ printf "%s-%s" .Values.managedstorage.cloudsqlInstanceConnectionName .Release.Name | replace ":" "-" | trunc 50 }}{{ end }}'
  databaseNamePrefix: null
  dbUsername: 'root'
  dbPassword: ''
