{{- if eq .Values.objectStore.type "seaweedfs" }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: seaweedfs
  labels:
    {{- include "kubeflow-pipelines.labels" . | nindent 4 }}
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchExpressions:
        - key: app.kubernetes.io/part-of
          operator: In
          values:
          - kubeflow-profile
    ports:
    - port: 8333
  - from:
    - namespaceSelector:
        matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: In
          values:
          - istio-system
  - from:
    - podSelector: {}
    ports:
    - port: 8333
  podSelector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - seaweedfs
  policyTypes:
  - Ingress
{{- end }}
