{{- if .Values.components.cache.enabled }}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: cache-webhook-kubeflow
  labels:
    {{- include "kubeflow-pipelines.labels" . | nindent 4 }}
  annotations:
    {{- include "kubeflow-pipelines.careem-annotations" . | nindent 4 }}
    {{- if .Values.webhook.certManager.enabled }}
    cert-manager.io/inject-ca-from: {{ include "kubeflow-pipelines.namespace" . }}/kfp-cache-webhook-cert
    {{- end }}
webhooks:
  - name: cache-server.{{ include "kubeflow-pipelines.namespace" . }}.svc
    clientConfig:
      service:
        name: cache-server
        namespace: {{ include "kubeflow-pipelines.namespace" . }}
        path: "/mutate"
    failurePolicy: Ignore
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    sideEffects: None
    timeoutSeconds: 5
    objectSelector:
      matchLabels:
        pipelines.kubeflow.org/cache_enabled: "true"
    admissionReviewVersions: ["v1"]
{{- end }}
