{{- if and .Values.mysql.external .Values.externalSecrets.enabled .Values.externalSecrets.mysql.secretStore }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.mysql.secretName }}
  namespace: {{ include "kubeflow-pipelines.namespace" . }}
  labels:
    {{- include "kubeflow-pipelines.labels" . | nindent 4 }}
  annotations:
    {{- include "kubeflow-pipelines.careem-annotations" . | nindent 4 }}
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: {{ .Values.externalSecrets.mysql.secretStore }}
    kind: SecretStore
  target:
    name: {{ .Values.mysql.secretName }}
    creationPolicy: Owner
  data:
    - secretKey: host
      remoteRef:
        key: {{ .Values.externalSecrets.mysql.remoteSecretKey }}
        property: host
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: port
      remoteRef:
        key: {{ .Values.externalSecrets.mysql.remoteSecretKey }}
        property: port
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: dbname
      remoteRef:
        key: {{ .Values.externalSecrets.mysql.remoteSecretKey }}
        property: dbname
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: username
      remoteRef:
        key: {{ .Values.externalSecrets.mysql.remoteSecretKey }}
        property: username
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: password
      remoteRef:
        key: {{ .Values.externalSecrets.mysql.remoteSecretKey }}
        property: password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None

---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Values.externalSecrets.mysql.secretStore }}
  namespace: {{ include "kubeflow-pipelines.namespace" . }}
  labels:
    {{- include "kubeflow-pipelines.labels" . | nindent 4 }}
  annotations:
    {{- include "kubeflow-pipelines.careem-annotations" . | nindent 4 }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.global.region }}
      auth:
        jwt:
          serviceAccountRef:
            name: ml-pipeline
{{- end }}
