{{- if .Values.components.persistenceagent.enabled }}
# Persistence Agent Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ml-pipeline-persistenceagent
  namespace: {{ include "kubeflow-pipelines.namespace" . }}
  labels:
    {{- include "kubeflow-pipelines.labels" . | nindent 4 }}
    app: ml-pipeline-persistenceagent
  annotations:
    {{- include "kubeflow-pipelines.careem-annotations" . | nindent 4 }}
    {{- include "kubeflow-pipelines.serviceaccount-annotations" . | nindent 4 }}

---
# Persistence Agent Role
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ml-pipeline-persistenceagent-role
  namespace: {{ include "kubeflow-pipelines.namespace" . }}
  labels:
    {{- include "kubeflow-pipelines.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - workflows
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - kubeflow.org
    resources:
      - scheduledworkflows
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - pipelines.kubeflow.org
    resources:
      - scheduledworkflows
      - workflows
    verbs:
      - report
  - apiGroups:
      - pipelines.kubeflow.org
    resources:
      - runs
    verbs:
      - reportMetrics
      - readArtifact

---
# Persistence Agent RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ml-pipeline-persistenceagent-binding
  namespace: {{ include "kubeflow-pipelines.namespace" . }}
  labels:
    {{- include "kubeflow-pipelines.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ml-pipeline-persistenceagent-role
subjects:
  - kind: ServiceAccount
    name: ml-pipeline-persistenceagent
    namespace: {{ include "kubeflow-pipelines.namespace" . }}

---
# Persistence Agent Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-pipeline-persistenceagent
  namespace: {{ include "kubeflow-pipelines.namespace" . }}
  labels:
    {{- include "kubeflow-pipelines.labels" . | nindent 4 }}
    app: ml-pipeline-persistenceagent
spec:
  replicas: {{ .Values.components.persistenceagent.replicas }}
  selector:
    matchLabels:
      app: ml-pipeline-persistenceagent
  template:
    metadata:
      labels:
        app: ml-pipeline-persistenceagent
        {{- include "kubeflow-pipelines.selectorLabels" . | nindent 8 }}
      annotations:
        {{- include "kubeflow-pipelines.config-checksum" . | nindent 8 }}
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: ml-pipeline-persistenceagent
      containers:
        - name: ml-pipeline-persistenceagent
          image: {{ .Values.images.registry }}/kfp-persistence-agent:{{ .Values.images.tag }}
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: TTL_SECONDS_AFTER_WORKFLOW_FINISH
              value: "86400"
            - name: NUM_WORKERS
              value: "2"
            - name: LOG_LEVEL
              value: "info"
          volumeMounts:
            - mountPath: /var/run/secrets/kubeflow/tokens
              name: persistenceagent-sa-token
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 0
            capabilities:
              drop:
                - ALL
          resources:
            {{- if .Values.components.persistenceagent.resources }}
            {{- toYaml .Values.components.persistenceagent.resources | nindent 12 }}
            {{- else }}
            requests:
              cpu: 120m
              memory: 500Mi
            {{- end }}
      volumes:
        - name: persistenceagent-sa-token
          projected:
            sources:
              - serviceAccountToken:
                  path: persistenceagent-sa-token
                  expirationSeconds: 3600
                  audience: pipelines.kubeflow.org
{{- end }}
