{{- if .Values.seaweedfs.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seaweedfs-pvc
  namespace: {{ include "kubeflow-pipelines.namespace" . }}
  labels:
    {{- include "kubeflow-pipelines.labels" . | nindent 4 }}
    app: seaweedfs
  annotations:
    {{- include "kubeflow-pipelines.careem-annotations" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.seaweedfs.storage.size | default "20Gi" }}
  {{- if .Values.seaweedfs.storage.storageClassName }}
  storageClassName: {{ .Values.seaweedfs.storage.storageClassName }}
  {{- end }}
{{- end }}
