{{- if .Values.seaweedfs.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: {{ include "kubeflow-pipelines.namespace" . }}
  labels:
    {{- include "kubeflow-pipelines.labels" . | nindent 4 }}
    app: seaweedfs
    component: minio-compatibility
  annotations:
    {{- include "kubeflow-pipelines.careem-annotations" . | nindent 4 }}
spec:
  ports:
    - name: http
      port: 9000
      protocol: TCP
      targetPort: 8333
  selector:
    app: seaweedfs
{{- end }}
