{{- if .Values.seaweedfs.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: seaweedfs
  namespace: {{ include "kubeflow-pipelines.namespace" . }}
  labels:
    {{- include "kubeflow-pipelines.labels" . | nindent 4 }}
    app: seaweedfs
  annotations:
    {{- include "kubeflow-pipelines.careem-annotations" . | nindent 4 }}
spec:
  ports:
    - name: http-iam
      port: 8111
      protocol: TCP
      targetPort: 8111
    - name: http-s3
      port: 8333
      protocol: TCP
      targetPort: 8333
    - name: http-master
      port: 9333
      protocol: TCP
      targetPort: 9333
    - name: grpc-master
      port: 19333
      protocol: TCP
      targetPort: 19333
    - name: grpc-filer
      port: 18888
      protocol: TCP
      targetPort: 18888
    - name: http-filer
      port: 8888
      protocol: TCP
      targetPort: 8888
  selector:
    app: seaweedfs
{{- end }}
