{{- if and .Values.components.apiserver.enabled .Values.kubernetesNative.enabled }}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: pipelineversions.pipelines.kubeflow.org
  labels:
    {{- include "kubeflow-pipelines.labels" . | nindent 4 }}
  annotations:
    {{- include "kubeflow-pipelines.careem-annotations" . | nindent 4 }}
    {{- if .Values.webhook.certManager.enabled }}
    cert-manager.io/inject-ca-from: {{ include "kubeflow-pipelines.namespace" . }}/kfp-api-webhook-cert
    {{- end }}
webhooks:
  - name: pipelineversions.pipelines.kubeflow.org
    rules:
      - operations:
          - CREATE
          - UPDATE
        apiGroups:
          - pipelines.kubeflow.org
        apiVersions:
          - v2beta1
        resources:
          - pipelineversions
        scope: Namespaced
    admissionReviewVersions:
      - v1
    sideEffects: None
    failurePolicy: Fail
    clientConfig:
      service:
        name: ml-pipeline
        namespace: {{ include "kubeflow-pipelines.namespace" . }}
        path: /webhooks/validate-pipelineversion
        port: 8443
{{- end }}
