apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# Application controller is used to provide Google Cloud Console integration.
- ../../third-party/application
- ../../base/application
- ../../base/installs/generic
- ../../base/metadata/base
- ../../third-party/argo/installs/namespace
- inverse-proxy
- cloudsql-proxy


# !!! If you want to customize the namespace,
# please also update base/cache-deployer/cluster-scoped/cache-deployer-clusterrolebinding.yaml
namespace: kubeflow

patches:
- path: gcp-configurations-patch.yaml

# Used by Kustomize
configMapGenerator:
- behavior: merge
  envs:
  - params.env
  name: pipeline-install-config

# Identifier for application manager to apply ownerReference.
# The ownerReference ensures the resources get garbage collected
# when application is deleted.
labels:
- includeSelectors: true
  pairs:
    application-crd-id: kubeflow-pipelines
