{{- if and .Values.compat.enabled .Values.compat.argo.priorityClass }}
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: workflow-controller
  labels:
    {{- if .Values.compat.applicationCrdIdLabel }}
    application-crd-id: kubeflow-pipelines
    {{- end }}
    {{- include "kubeflow-pipelines.labels" . | nindent 4 }}
value: 1000000
{{- end }}
