apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-pipeline
spec:
  template:
    spec:
      containers:
        - name: ml-pipeline-api-server
          env:
            - name: CACHEENABLED
              value: "false"
            - name: HTTP_PROXY
              value: "http://squid.squid.svc.cluster.local:3128"
            - name: HTTPS_PROXY
              value: "http://squid.squid.svc.cluster.local:3128"
            - name: NO_PROXY
              value: "localhost,127.0.0.1,.svc.cluster.local,kubernetes.default.svc,seaweedfs.kubeflow,metadata-grpc-service,metadata-grpc-service.kubeflow,ml-pipeline.kubeflow"
            - name: OBJECTSTORECONFIG_HOST
              value: "seaweedfs.kubeflow.svc.cluster.local"
