apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../cache-disabled

patches:
  - path: apiserver-env.yaml
    target:
      kind: Deployment
      name: ml-pipeline
  - path: ../../base/driver-plugin-cm-path.yaml
    target:
      kind: ConfigMap
      name: ml-pipeline-driver-agent
