apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
  - metadata-grpc-configmap.yaml
  - metadata-grpc-deployment.yaml
  - metadata-grpc-service.yaml
  - metadata-envoy-configmap.yaml
  - metadata-envoy-deployment.yaml
  - metadata-envoy-service.yaml
  - metadata-grpc-sa.yaml
images:
  - name: ghcr.io/kubeflow/kfp-metadata-envoy
    newTag: 2.15.0
