apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - metadata-grpc-configmap.yaml
  - metadata-grpc-deployment.yaml
  - metadata-grpc-service.yaml
  - metadata-envoy-deployment.yaml
  - metadata-envoy-service.yaml
  - metadata-grpc-sa.yaml
images:
  - name: gcr.io/ml-pipeline/metadata-envoy
    newTag: 2.0.0-alpha.6
