apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../../namespaced
  - ../mysql

resources:
  - viewer-tensorboard-template-configmap.yaml

# Replace with your namespace
namespace: kubeflow

patchesStrategicMerge:
  - aws-configurations-patch.yaml

configMapGenerator:
- name: pipeline-aws-parameters
  env: params.env

generatorOptions:
  disableNameSuffixHash: true

vars:
- name: awsSecretName
  objref:
    kind: ConfigMap
    name: pipeline-aws-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.awsSecretName
- name: awsAccessKeySecretKey
  objref:
    kind: ConfigMap
    name: pipeline-aws-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.awsAccessKeySecretKey
- name: awsSecretKeySecretKey
  objref:
    kind: ConfigMap
    name: pipeline-aws-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.awsSecretKeySecretKey
- name: awsRegion
  objref:
    kind: ConfigMap
    name: pipeline-aws-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.awsRegion
- name: executorImage
  objref:
    kind: ConfigMap
    name: pipeline-aws-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.executorImage
- name: artifactRepositoryBucket
  objref:
    kind: ConfigMap
    name: pipeline-aws-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.artifactRepositoryBucket
- name: artifactRepositoryKeyPrefix
  objref:
    kind: ConfigMap
    name: pipeline-aws-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.artifactRepositoryKeyPrefix

configurations:
- params.yaml