name: Build and Push images
run-name: Build images
on:
  workflow_call:
    inputs:
      src_branch:
        type: string
        default: ''
        description: 'Source branch to build KFP from'
        required: false
      target_tag:
        type: string
        description: 'Target Image Tag'
        required: true
      overwrite_imgs:
        type: string
        default: 'true'
        description: 'Overwrite images in GHCR if they already exist for this tag.'
        required: false
      set_latest:
        type: string
        default: 'true'
        description: 'Set latest tag on build images.'
        required: false
      add_sha_tag:
        type: string
        default: 'true'
        description: 'Add a sha image tag.'
        required: false
      app_to_build:
        type: string
        description: 'Provide the app name to build'
        required: true
      image_context:
        type: string
        description: 'Provide the docker file path'
        required: true
      docker_file:
        type: string
        description: 'Provide the docker file name'
        required: true
      platforms:
        type: string
        required: true
        description: e.g, linux/amd64 or linux/arm64
      push:
        type: boolean
        default: false
        description: 'Whether to push image to CR or not'
        required: false
  workflow_dispatch:
    inputs:
      src_branch:
        type: string
        default: ''
        description: 'Source branch to build KFP from'
        required: true
      target_tag:
        type: string
        default: 'X.Y.Z'
        description: 'Target Image Tag'
        required: true
      fail_fast:
        type: string
        default: 'true'
        description: 'Stop running entire Workflow if a single build fails'
        required: true
      overwrite_imgs:
        type: string
        default: 'true'
        description: 'Overwrite images in GHCR if they already exist for this tag.'
        required: true
      set_latest:
        type: string
        default: 'true'
        description: 'Set latest tag on build images.'
        required: true
      add_sha_tag:
        type: string
        default: 'true'
        description: 'Add a sha image tag.'
        required: false
      app_to_build:
        type: string
        default: ''
        description: 'Provide the app name to build'
        required: true
      image_context:
        type: string
        default: ''
        description: 'Provide the docker file path'
        required: true
      docker_file:
        type: string
        default: ''
        description: 'Provide the docker file name'
        required: true
      platforms:
        type: string
        default: ''
        required: true
        description: 'Provide the target architecture e.g, linux/amd64, linux/arm64'
      push:
        type: boolean
        default: false
        description: 'Whether to push image to CR or not'
        required: true
env:
  SOURCE_BRANCH: ${{ inputs.src_branch }}
  TARGET_IMAGE_TAG: ${{ inputs.target_tag }}
  OVERWRITE_IMAGES: ${{ inputs.overwrite_imgs }}
  IMAGE_REGISTRY: ghcr.io
  IMAGE_ORG: ${{ github.repository_owner }}
  SET_LATEST: ${{ inputs.set_latest }}
  ADD_SHA_TAG: ${{ inputs.add_sha_tag }}
  CACHE_PATH: '/tmp/.buildx-cache'
  BUILDX_BUILDER: 'poly-builder'
  IP_AMR64_NODE: ${{ vars.IP_AMR64_NODE }}

jobs:
  build-and-push-images:
    continue-on-error: false
    runs-on: [self-hosted, Linux, X64]
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          ref: ${{env.SOURCE_BRANCH}}

      - name: Get checked-out commit SHA
        id: get_commit
        run: echo "sha=$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
       
      # 1. Add remote node to known_hosts to prevent interactive prompt hanging
      - name: Add Known Hosts
        env:
           ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "IP_ARM64_NODE: $IP_AMR64_NODE"
          echo "SSH_PRIVATE_KEY: $SSH_PRIVATE_KEY "
          echo "SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}" 
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts
        

      # 2. Setup SSH Agent so Docker can connect to the remote node
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # 3. Set up Docker Buildx
      # We manually create the builder to ensure the SSH connection works
      - name: Create Multi-Arch Builder
        run: |
          docker buildx create --name poly-builder \
            --driver docker-container \
            --platform linux/amd64 \
            --node node-amd64
            
          # Use IP_AMR64_NODE for ARM node's IP address
          docker buildx create --name poly-builder \
            --append \
            --platform linux/arm64 \
            --node node-arm64 \
            ssh://ubuntu@$IP_AMR64_NODE
            
          docker buildx use poly-builder
          docker buildx inspect --bootstrap 
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug


      - name: Check if image tag already exists
        id: check_tag
        env:
          IMAGE: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_ORG }}/${{ inputs.app_to_build }}:${{env.TARGET_IMAGE_TAG}}
          OVERWRITE: ${{ env.OVERWRITE_IMAGES }}
        run: |
          if docker manifest inspect "${IMAGE}" > /dev/null 2>&1; then
            echo "Image tag already exists!"
            if [ "$OVERWRITE" == "false" ]; then
              echo "Overwrite is set to false, exiting."
              exit 1
            else
              echo "Overwrite is set to true, proceeding with push."
            fi
          else
            echo "No tag conflict, safe to push."
          fi

      # This step uses docker/metadata-action to extract tags and labels
      # that will be applied to the specified image. The id "meta" allows
      # the output of this step to be referenced in a subsequent step.
      # The images value provides the base name for the tags and labels.
      - name: Extract metadata (tags, labels) for Build
        id: meta
        uses: docker/metadata-action@v5
        if: steps.check_tag.outcome == 'success'
        with:
          images: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_ORG }}/${{ inputs.app_to_build }}
          tags: |
            type=raw,value=${{env.TARGET_IMAGE_TAG}}
            type=raw,value=latest,enable=${{ env.SET_LATEST == 'true'}}
            type=sha,enable=${{ env.ADD_SHA_TAG == 'true' }}

      # Build the image. If the build succeeds, it pushes the image to GitHub
      # Packages. It uses the context parameter to define the build's context
      # as the set of files located in the specified path.
      - name: Build and push Image
        id: push
        uses: docker/build-push-action@v6
        if: steps.check_tag.outcome == 'success'
        with:
          platforms: ${{ inputs.platforms }}
          context: ${{ inputs.image_context }}
          file: ${{ inputs.docker_file }}
          push: ${{ inputs.push }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            COMMIT_SHA=${{ steps.get_commit.outputs.sha }}
            COMMIT_HASH=${{ steps.get_commit.outputs.sha }}
            TAG_NAME=${{ inputs.target_tag }}

      # This step generates an artifact attestation for the image,
      # which is an unforgeable statement about where and how it was built.
      # It increases supply chain security for people who consume the
      # image.
      # Ref: https://docs.github.com/en/actions/security-for-github-actions/using-artifact-attestations/using-artifact-attestations-to-establish-provenance-for-builds
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        if: steps.check_tag.outcome == 'success' && inputs.push
        with:
          subject-name: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_ORG }}/${{ inputs.app_to_build }}
          subject-digest: ${{ steps.push.outputs.digest }}
