name: KFP SDK Tests

on:
  push:
    branches: [master]
  pull_request:
    paths:
      - 'api/**'
      - 'sdk/**'
      - 'test_data/sdk_compiled_pipelines/**'
      - './test/presubmit-tests-sdk.sh'
      - '.github/workflows/kfp-sdk-tests.yml'
      - '!**/*.md'
      - '!**/OWNERS'

concurrency:
  group: sdk-tests-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  sdk-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    strategy:
      matrix:
        python-version: ['3.9', '3.13']

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Setup Python with uv
      uses: ./.github/actions/setup-python
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install protobuf dependencies & generate proto files
      id: install-protobuf-deps
      uses: ./.github/actions/protobuf

    - name: Run SDK Tests
      env:
        # We setup the env in the CI
        SETUP_ENV: false
        REPO_NAME: ${{ github.repository }}
        PULL_NUMBER: ${{ github.event.pull_request.number }}
      run: |
        ./test/presubmit-tests-sdk.sh
