name: KFP SDK Unit Tests

on:
  push:
    branches: [master]
  pull_request:
    paths:
      - 'api/**'
      - 'sdk/**'
      - './test/presubmit-tests-sdk-unit.sh'
      - '.github/workflows/kfp-sdk-unit-tests.yml'
      - '!**/*.md'
      - '!**/OWNERS'

concurrency:
  group: sdk-unit-tests-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  sdk-unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.13']

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Setup Python with uv
      uses: ./.github/actions/setup-python
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install protobuf dependencies & generate proto files
      uses: ./.github/actions/protobuf

    - name: Run SDK Tests
      id: run-tests
      env:
        # We setup the env in the CI
        SETUP_ENV: false
        REPO_NAME: ${{ github.repository }}
        PULL_NUMBER: ${{ github.event.pull_request.number }}
        JUNIT_XML: "sdk-unit.xml"
      run: |
        ./test/presubmit-tests-sdk-unit.sh
        echo "JUNIT_XML=$JUNIT_XML" >> "$GITHUB_OUTPUT"

    - name: Publish Junit Summary
      id: summary
      uses: ./.github/actions/junit-summary
      if: (!cancelled())
      with:
        xml_files: ${{ steps.run-tests.outputs.JUNIT_XML }}
      continue-on-error: true
