name: KFP Manifests

on:
  push:
    branches: [master]
  pull_request:
    paths:
      - '.github/workflows/kubeflow-pipelines-manifests.yml'
      - 'manifests/kustomize/**'
      - '!**/*.md'
      - '!**/OWNERS'

jobs:
  kubeflow-pipelines-manifests:    
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5    

      - name: Run tests
        run: make test-kubeflow-pipelines-manifests
