apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadata-writer
  labels:
    app: metadata-writer
    {{- include "kubeflow-pipelines.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.metadataWriter.replicas }}
  selector:
    matchLabels:
      app: metadata-writer
  template:
    metadata:
      labels:
        app: metadata-writer
    spec:
      {{- include "kubeflow-pipelines.imagePullSecrets" . | nindent 6 }}
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: main
        image: "{{ .Values.metadataWriter.image.repository }}:{{ .Values.metadataWriter.image.tag }}"
        env:
        {{- if .Values.multiUser.enabled }}
        - name: NAMESPACE_TO_WATCH
          value: ""
        {{- else }}
        - name: NAMESPACE_TO_WATCH
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        {{- end }}
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 0
          capabilities:
            drop:
            - ALL
        {{- with .Values.metadataWriter.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      serviceAccountName: kubeflow-pipelines-metadata-writer
      {{- with .Values.metadataWriter.nodeSelector | default .Values.global.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.metadataWriter.tolerations | default .Values.global.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.metadataWriter.affinity | default .Values.global.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
